### ISSUE TITLE
Integrate Travis CI

### ISSUE THREAD

**Issue by PrabhanshuAttri** [nirmankarta/PyBeacon#13]
Travis CI for everybuild
- [ ] Create .travis.yml.
- [ ] Test it.

Reference: [Travis Python Doc](https://docs.travis-ci.com/user/languages/python/)
Report by: @krishamehta [ #2 ]

**Comment by gururajbn** [comment]
@PrabhanshuAttri can i give it a try ?

**Comment by PrabhanshuAttri** [comment]
@gururajbn Go ahead. Let us know when it's done.

**Comment by gururajbn** [comment]
@PrabhanshuAttri i added `.travis.yml` file #14 . Can you tell me what key i should add for `script` to run tests.

**Comment by ashleyyy94** [comment]
Hi, is this issue closed, or pending the merging of the above travis file? ^ I was thinking of attempting this too. But I saw that the dev branch has been closed.

**Comment by PrabhanshuAttri** [comment]
@ashleyyy94 Hi this is still open. Free free to attempt and let us know if you were able to do it.

**Comment by ashleyyy94** [comment]
For the second point: Test it. Do you mean write tests for PyBeacon? Currently travis build is up and working already with the script just running "echo foo"

**Comment by PrabhanshuAttri** [comment]
@gururajbn @ashleyyy94 This will include tests for PyBeacon to ensure the build doesn't have any bugs. Python 3.x is supported while 2.x has this [issue](https://github.com/nirmankarta/PyBeacon/issues/1). Both of you can work together on this. Let me know if you need a channel on slack to communicate.

**Comment by ashleyyy94** [comment]
I'll like the channel please :) Currently I have PyBeacon installed on Ubuntu, it can advertise but cannot seem to scan a Eddystone URL advertised from my phone.

**Comment by PrabhanshuAttri** [comment]
@ashleyyy94 @gururajbn please tell me your email addresses, will send a slack invite.

**Comment by gururajbn** [comment]
@PrabhanshuAttri (n.gururajbn@gmail.com) I am quite busy coming weeks, @ashleyyy94  can take over this issue. I am really sorry.

**Comment by ashleyyy94** [comment]
Hey no problem :) I'm just trying it out in my spare time. My email is ashley_2461994@hotmail.com.

**Comment by PrabhanshuAttri** [comment]
@ashleyyy94 Please check your mail. Let's discuss this on slack.
