### ISSUE TITLE
Add .gitignore file for unnecessary files

### ISSUE THREAD

**Issue by PrabhanshuAttri** [nirmankarta/PyBeacon#17]
Add .gitignore file to ignore following unnecessary files
- [ ] .DS_Store
- [ ] .pyc
- [ ] .cache

**Comment by nagoli104** [comment]
Is this still required/unassigned?

**Comment by PrabhanshuAttri** [comment]
@ashleyyy94 was working on it. Create a PR if you think you can do it. Take help from [here](https://github.com/nirmankarta/PyBeacon/pull/16/files).

**Comment by PrabhanshuAttri** [comment]
#19
