### ISSUE TITLE
Fix NameError in test_pybeacon.py

### ISSUE THREAD

**Issue by PrabhanshuAttri** [nirmankarta/PyBeacon#24]
This error is thrown while testing PyBeacon methods.
**NameError**: global name 'encodeUid' is not defined

**Comment by schedutron** [comment]
Let me do this.

**Comment by PrabhanshuAttri** [comment]
Go head. Create a PR when it's done.

**Comment by schedutron** [comment]
@PrabhanshuAttri How do I build this locally? Are there some special techniques required apart from just cloning?

**Comment by PrabhanshuAttri** [comment]
- Clone the repo
- Install the test dependencies (use sudo if you face issue)
```
pip install coveralls pytest pytest-cov

```
- run the following command to test
```
py.test
```

Tests/test_pybeacon contains 2 methods in the end which are commented. You will have to fix these methods

**Comment by schedutron** [comment]
Why are CI checks failing?

**Comment by PrabhanshuAttri** [comment]
Assert is comparing empty array with a valid array.

**Comment by schedutron** [comment]
@PrabhanshuAttri Is it a problem with test definitions, or any of the lines I've added?

**Comment by PrabhanshuAttri** [comment]
Test definitions. Let me know if you can fix them. Also, please create the PR against dev branch.

**Comment by PrabhanshuAttri** [comment]
@schedutron Let me know if you need help.

**Comment by schedutron** [comment]
@PrabhanshuAttri I've added PR #28 against the dev branch now.
