### ISSUE TITLE
Add README badges

### ISSUE THREAD

**Issue by PrabhanshuAttri** [nirmankarta/PyBeacon#26]
Add README badges for the following:
- [x] Package version ([See this](https://badge.fury.io/for/py/PyBeacon))
- [x] Slack Invite link
- [x] Versions of Python supported
- [x] Contributors
- [x] OS supported
- [x] License

See README badges [here](https://shields.io). It's not necessary to use shields README badges only.

**Comment by Rarer** [comment]
I can take a look at that

**Comment by rivermont** [comment]
Where can the Slack link be found? Also, I can run tests for Ubuntu 16.04 and Windows 10.

**Comment by dhruvhacks** [comment]
@PrabhanshuAttri May I know the slack invite link for adding Slack's badge to readme?

**Comment by PrabhanshuAttri** [comment]
http://nirmankarta.herokuapp.com

@rivermont you can add slack and versions of python; @dhruvhacks you can add OS supported and License.

**Comment by mstuttgart** [comment]
@PrabhanshuAttri I will add `package version` and `license` badge

**Comment by campionfellin** [comment]
@PrabhanshuAttri  I'll add the contributors badge!

**Comment by PrabhanshuAttri** [comment]
@campionfellin @rivermont  has already claimed contributors badge. Please claim any other issue.

**Comment by campionfellin** [comment]
@PrabhanshuAttri Hey, sorry did not see that! I'll look into other issues.
