### ISSUE TITLE
Add support for Eddystone-UID

### ISSUE THREAD

**Issue by sestus** [nirmankarta/PyBeacon#3]
Hello, I 'm thinking of adding support for eddystone-uid. I m working on a prototype with eddystone-uid, and your program is handy, so I 'd like to extend it to support uid.

Besides that, the name of the repo is PyBeacon, so I suppose it's not limited just to eddystone-URL :) I 've forked the repo and I ll create a pull request as soon as I m ready.

How does this sound? If you have any concerns / notes please let me know!

**Comment by PrabhanshuAttri** [comment]
Awesome! Let me know when you complete it. I will test it and merge it if it's stable.
