### ISSUE TITLE
Move PyPi badge after travis badge

### ISSUE THREAD

**Issue by PrabhanshuAttri** [nirmankarta/PyBeacon#36]
Move PyPi badge after Travis build badge in README.md

**Comment by thomasstep** [comment]
Do you just want the badges shifted around?

**Comment by PrabhanshuAttri** [comment]
@thomasstep yes

**Comment by Raindeer44** [comment]
I know #38 already exists, but I'd like to take a stab at this real quick, using the feedback on #38

**Comment by PrabhanshuAttri** [comment]
@Raindeer44 Let's wait for @thomasstep to reply as he has claimed the issue. Feel free to fix other issues. Good work.

Both PR will be considered as hacktoberfest contributions.

**Comment by thomasstep** [comment]
I'm sorry for the late reply. I went afk after I made that PR.

**Comment by PrabhanshuAttri** [comment]
Thank you @thomasstep and @Raindeer44
