### ISSUE TITLE
Create contribution.md

### ISSUE THREAD

**Issue by PrabhanshuAttri** [nirmankarta/PyBeacon#40]
Tasks
- [ ] Read about contribution.md.
- [ ] Discuss various guidelines which can be added in the comment section below. 
- [ ] Create Contribution.md file

[Code of conduct](http://todogroup.org/opencodeofconduct/) which can be used.

Resources:
- [Atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)
- [Python Foundation](http://docs.python-guide.org/en/latest/notes/contribute/)
- [Rails](https://github.com/rails/rails/blob/master/CONTRIBUTING.md)
- [Open Government](https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md)

**Comment by rivermont** [comment]
Here are a few starters:

* Create an issue first to allow for better management.
* Make sure to make PRs against the dev branch first.
* No trivial edits, ie. simply rearranging topics.

**Comment by PrabhanshuAttri** [comment]
@rivermont could you please go through the above resources and come up with a list of guidelines we can use?
Also, few minor changes can be allowed. Sometimes it helps those who are new to open source.
Thanks.

**Comment by rivermont** [comment]
Will look at this tomorrow morning!

**Comment by mstuttgart** [comment]
@PrabhanshuAttri take a look in this[ CONTRIBUTING](https://github.com/pynocchio/pynocchio/blob/develop/CONTRIBUTING.rst). I use it in my projects. We use like base to create our CONTRIBUTING file.

**Comment by PrabhanshuAttri** [comment]
@mstuttgart This looks good. Could you please create a PR using this markdown file? Also, move the 'Getting started' guidelines above 'Types of contributions'. Once we merge this, @rivermont can help us with updating the markdown.

It's kinda unmanageable without a Contribution guidelines.
Both of you please join our slack channel so that we can discuss them easily.

**Comment by mstuttgart** [comment]
@PrabhanshuAttri I work this

**Comment by PrabhanshuAttri** [comment]
@rivermont @mstuttgart has created the file. Could you please add the changes you have suggested? Also, add a link in README.md with the following note:
'Please read [contribution.md](link) before making any kind of contribution. '.

Let me know if you have any other suggestions.

**Comment by PrabhanshuAttri** [comment]
Hi @rivermont 
Just touching base for a quick update on this. Thanks

**Comment by fatimarafiqui** [comment]
Can I take this issue?

**Comment by PrabhanshuAttri** [comment]
@fatimarafiqui sure,  go ahead.
