### ISSUE TITLE
Add python versions to corresponding badge

### ISSUE THREAD

**Issue by fatimarafiqui** [nirmankarta/PyBeacon#47]
We can add a combined python badge for all python versions. something like this- 
![Python Badge](https://img.shields.io/badge/Python-2.6%2C%202.7%2C%203.3%2C%203.4%2C%203.5%2C%203.6-green.svg)

I would like to create a pull request for the same.

**Comment by PrabhanshuAttri** [comment]
@fatimarafiqui Go ahead and create a PR for the same.
