### ISSUE TITLE
Remove PyBeacon/__main__.py

### ISSUE THREAD

**Issue by HimanshuAttri** [nirmankarta/PyBeacon#55]
`PyBeacon/__main__.py` is of no use. We can remove it.

**Comment by PrabhanshuAttri** [comment]
Thanks for pointing this out. Please remove and test it before sending the PR.

**Comment by mayankagarwal2402** [comment]
Hi @HimanshuAttri. First time OSS contributor here. I would like to take on this issue.
Please find the [PR](https://github.com/nirmankarta/PyBeacon/pull/57) as per your contribution guidelines.
