### ISSUE TITLE
Refactoring to adhere to the PEP 8 style guidelines

### ISSUE THREAD

**Issue by PrabhanshuAttri** [nirmankarta/PyBeacon#8]
Refactor PyBeacon.py, so as to adhere to the PEP 8 style guidelines. 
@sestus would you like to do it?

**Comment by sestus** [comment]
Hello! I 'd love to do it, but I 've been pretty busy lately, due to a hackathon that me and my team are going to participate. I expect to be fully committed to this hackathon until March.

So in case this is still open, I 'd be happy to refactor, yes!

**Comment by PrabhanshuAttri** [comment]
Take your time. I just wanted to get this merged in google/eddystone. It would be great if you do it sooner.

**Comment by sigmapie8** [comment]
Hey , although I am noob at open source contributions , but I think I can do it. 
Just to be clear, you want to just change the code written according to PEP8 , right?

**Comment by PrabhanshuAttri** [comment]
@sigmapie8 Yes, that's exactly what we want. [PEP8 Link](https://www.python.org/dev/peps/pep-0008/). Send a PR once you are done.
